[api]
port = 54321
schemas = ["public"]

[db]
port = 54322
major_version = 17

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:3000"]
jwt_expiry = 3600

[auth.external.google]
enabled = false

[auth.external.apple]
enabled = false
